### PR TITLE
Fixed static usage of triangle points

### PR DESCRIPTION
**Pull request by alxhoff**
@PhilippvK  this should do it

### CODE REVIEW

**Comment by PhilippvK** [comment]
Shouldn’t one use the thread save memory allocation methods provided by FreeRTOS e.g. `pvPortMalloc()`?

**Review by PhilippvK — APPROVED** [review]
Works as expected

**Comment by alxhoff** [comment]
> Shouldn’t one use the thread save memory allocation methods provided by FreeRTOS e.g. `pvPortMalloc()`?

This stuff is implemented behind FreeRTOS and as such I tried to make sure they didn't need to include FreeRTOS to avoid circular inclusion etc.

**Comment by alxhoff** [comment]
> Shouldn’t one use the thread save memory allocation methods provided by FreeRTOS e.g. `pvPortMalloc()`?

This stuff is implemented behind FreeRTOS and as such I tried to make sure they didn't need to include FreeRTOS to avoid circular inclusion etc.

**Pull request merged**
