### PR TITLE
Handled checking for context ownership before reinitializing renderer

### PR DESCRIPTION
**Pull request by alxhoff**
@PhilippvK any chance you could pull this on a system or two and check it works pleaseeeee?

### CODE REVIEW

**Comment by PhilippvK** [comment]
I compiles and runs without crashes on my Ubuntu20 system. However I did not know if I should look for something special as I did not know if there was an issue.

(While running the emulator my second screen blackscreened several times, not sure if this is related to this PR :p )

**Comment by alxhoff** [comment]
Did the machine where it was buggy have a GPU?

**Comment by alxhoff** [comment]
Having issues with machines with GPUs atm

**Comment by PhilippvK** [comment]
Nope, 3 screens connected via main board haha

**Comment by alxhoff** [comment]
Did that last commit help?

**Comment by PhilippvK** [comment]
> Did that last commit help?

Nope it actually got worse (something like screen tearing appeared in the emulator itself).

The blackscreen was not an actual blackscreen, just my firefox window went black. So this is maybe a window manager (XFCE) issue which also appreas on `master`. As the emulator is still usable it is not a major issue.

**Comment by alxhoff** [comment]
Maybe because I removed VSYNC, try this incoming commit plox <3

**Comment by alxhoff** [comment]
So on my machine with software rendering it works and in my VM with software rendering it fails :S

**Pull request merged**
