### PR TITLE
Rough code for #69

### PR DESCRIPTION
**Pull request by alxhoff**

### CODE REVIEW

**Comment by alxhoff** [comment]
:sunglasses:

**Comment by PhilippvK** [comment]
@alxhoff Please commit your sprite sheet.

**Comment by alxhoff** [comment]
ah crap. rebase untracked it

**Comment by alxhoff** [comment]
I should just build a game engine :P

**Comment by PhilippvK** [comment]
Why ist the left Animation flickering with a white frame in between while the right one runs relatively smooth?

**Comment by alxhoff** [comment]
> Why ist the left Animation flickering with a white frame in between while the right one runs relatively smooth?

Ahhh I never realized that it is a discrepancy. Going point. I shall investigate.

**Comment by alxhoff** [comment]
Fixed. Accidentally set the wrong frame as the start frame in the reverse sequence.

**Pull request closed without merging**
