### PR TITLE
Reimplement Pong Demo

### PR DESCRIPTION
**Pull request by PhilippvK**

### CODE REVIEW

**Comment by PhilippvK** [comment]
I have not fixed these bugs yet: #50

**Comment by alxhoff** [comment]
image

**Comment by alxhoff** [comment]
Shall I wait to review?

**Comment by PhilippvK** [comment]
I dont think so. The only file I have merged is main.c so ignore the rest which is just the changes which happened on the master branch over the last weeks.

**Comment by alxhoff** [comment]
the merge conflicts in main are pretty huge. any chance you can resolve this @PhilippvK?

**Comment by PhilippvK** [comment]
Hmm there are two options:

Just replace the current main.c with the new one. Or trow the pong branch away and rename pong2 (the new pong implementation) to pong (we would loose some commit history this way)

**Comment by PhilippvK** [comment]
better?

**Comment by alxhoff** [comment]
i'll check it now. Thanks for the update

**Comment by alxhoff** [comment]
look good! Thanks!

**Comment by alxhoff** [comment]
I will move this to the pong branch

**Pull request merged**
