### PR TITLE
Feature global offset

### PR DESCRIPTION
**Pull request by alxhoff**
As suggested in #70.

This would make the exercises stupidly easy though.....

### CODE REVIEW

**Comment by alxhoff** [comment]
@PhilippvK GH is back lolololol

**Review by PhilippvK — APPROVED** [review]

**Comment by PhilippvK** [comment]
What an annoying work to add all those offset statements.... :)

**Comment by PhilippvK** [comment]
Make sure to update the docs as well and remove the example part from the main.

**Comment by PhilippvK** [comment]
>> Make sure to update the docs as well and remove the example part from the main.

Lol, you just did that!

**Comment by alxhoff** [comment]
> What an annoying work to add all those offset statements.... :)

yes it was :P 

docs are deployed by CI :sunglasses:

**Comment by alxhoff** [comment]
> > > Make sure to update the docs as well and remove the example part from the main.
> 
> Lol, you just did that!

:nerd_face:

**Pull request merged**
