### PR TITLE
Fix event polling by moving it to draw loop

### PR DESCRIPTION
**Pull request by PhilippvK**
Same here: ask me for my intentions.

Without this, i had constant crashes on every OS except Ubuntu.

I understand, that it would be nicer to have a separate update loop for events (at a higher refresh rate than 20ms). We COULD realize this by having 2 Semaphores notifying between the Frame Swapper Task and the Event Polling Routine but this would probably also add some overheads...

### CODE REVIEW

**Comment by PhilippvK** [comment]
Gonna have to resolve conflicts first. Thanks for merging the other stuff!

**Comment by alxhoff** [comment]
hahah yer there are a few :P

**Comment by PhilippvK** [comment]
Do not bother with them. I will.

**Comment by alxhoff** [comment]
#5 not fixed yet :/

**Comment by PhilippvK** [comment]
I think I have to install manjaro...

**Comment by alxhoff** [comment]
> I think I have to install manjaro...

it is a good distro :)

**Comment by PhilippvK** [comment]
But I am running out of disk space :p

Am Mi., 1. Apr. 2020 um 17:18 Uhr schrieb Alex Hoffman <
notifications@github.com>:

**Comment by alxhoff** [comment]
Time to switch to manjaro then

**Pull request merged**
