### PR TITLE
Feature frame limit

### PR DESCRIPTION
**Pull request by alxhoff**
And a hear of random formatting.

### CODE REVIEW

**Comment by PhilippvK** [comment]
I am getting fps reading over 50 (51-61) especially after launching the program. Is this caused by initializing the averaging window with zeros?

**Comment by alxhoff** [comment]
Should be hitting 60. The averaging window doesn't average the zeros at the beginning. I was getting about 50 FPS, not sure why I want getting 60.

**Comment by PhilippvK** [comment]
But shouldn’t the framerate be still managed in main.c to be max 50 fps (20 ticks)?

**Comment by alxhoff** [comment]
Oh right I forgot about that 😂😂 yes you're 100% correct

**Pull request merged**
